### PR TITLE
Add glob options interface to fileLoader options signature

### PR DESCRIPTION
**Pull request by 4urbanoff**
Hi, guys!
Small convenience for the developer )

### CODE REVIEW

**Comment by RichardLitt** [comment]
What's the main difference as far as usability goes, here? :)

**Comment by 4urbanoff** [comment]
@RichardLitt intellisense when entering parameters)
The developer does not need to separately go into the glob-documentation to find out the list of parameters. I have experienced it today.

**Comment by cfnelson** [comment]
@4urbanoff Does this PR work if you don't have `@types/glob` installed on your machine?
I don't use typescript so I'm unable to assert if this works as intended. I base the question above due to reading this article -> https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Unsure if there is a requirement to have types added as deps, peerDeps, or optionalDeps or no requirement at all. Any clarification would be greatly appreciated to clear up my confusion! 😃

**Comment by 4urbanoff** [comment]
@cfnelson, sorry, I missed this point because vscode automatically tightens types if they are not in the project's `node_modules`. Yes indeed, an explicit indication a `@types/glob` package in dependencies is preferable to hoping that the editor will deal with them himself. I edited last commit and added @types/glob to dependencies.

**Comment by cfnelson** [comment]
@4urbanoff Is it possible to have the type as a peerDeps so that we don't have to bundle and include it in the bundle? Will that be sufficient for it to work correctly for someone using TypeScript? Would ideally like to avoid bundling new pkgs into the deps of this project.

**Comment by 4urbanoff** [comment]
@cfnelson No, if you add @types/glob to peerDeps, then each developer will be forced to install @types/glob in their dependencies. Thanks for this, no one will say) Do not see anything wrong with adding this package. You use the glob package in the project, why not add its types.

**Comment by ardatan** [comment]
Thank you for your PR :) Instead of having seperate TS typings, we migrated all codebase to TypeScript in this PR 
https://github.com/Urigo/merge-graphql-schemas/pull/203

**Pull request closed without merging**
